_schema: _schema
source: /
paths:
  uploads: static/uploads
  static: static
collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_content_blog:
    path: src/content/blog
    name: Src Content Blog
    icon: account_box
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_content_pages:
    path: src/content/pages
    name: Src Content Pages
    icon: contact_page
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_content_sections:
    path: src/content/sections
    name: Src Content Sections
    icon: collections
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_content_settings:
    path: src/content/settings
    name: Src Content Settings
    icon: content_paste_go
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  header:
    path:
    glob:
      -
    name:
    singular_name:
    icon: notes
    url:
    disable_url: false
    include_developer_files: true
    documentation:
    description:
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
timezone: Asia/Calcutta
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
