# Build settings
[build]
  command = "npm run build"
  publish = "public"

# Ensure HTTPS for all requests
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Redirect www to non-www version
[[redirects]]
  from = "https://www.startsolo.in/*"
  to = "https://startsolo.in/:splat"
  status = 301
  force = true

# Ensure Netlify CMS /admin loads correctly
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Redirect uploaded media to correct folder
[[redirects]]
  from = "/uploads/*"
  to = "/static/uploads/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https://unpkg.com; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https:; frame-src 'self' https:; object-src 'none'; upgrade-insecure-requests;"

# Allow Netlify CMS scripts and media uploads
[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "connect-src 'self' blob: https://api.netlify.com https://unpkg.com; script-src 'self' 'unsafe-inline' https://unpkg.com; style-src 'self' 'unsafe-inline' https:;"

# Environment variables (Custom domain settings)
[build.environment]
  NETLIFY_SITE_URL = "https://startsolo.in"
