backend:
  name: git-gateway
  branch: main # Branch to update

# Site URL Configuration
site_url: https://startsolo.in
display_url: https://startsolo.in

# Media storage
media_folder: "public/uploads"
public_folder: "/uploads"

# Enable local backend for development
local_backend: true

collections:
  # 🔹 SITE SETTINGS (SINGLE FILE)
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "content/settings/general.json"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: "string" }
          - { label: "Logo Image", name: "logoImage", widget: "image" }
      - name: "footer"
        label: "Footer & Socials"
        file: "content/settings/footer.json"
        fields:
          - { label: "Footer Logo", name: "footerLogo", widget: "image" }
          - { label: "Quick Links", name: "quickLinks", widget: "list", fields: [{ label: "Label", name: "label", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }
          - { label: "Social Media", name: "socialMedia", widget: "object", fields: [{ label: "Twitter", name: "twitter", widget: "string" }, { label: "Instagram", name: "instagram", widget: "string" }] }

  # 🔹 PAGES (DYNAMIC FOLDER)
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }

  # 🔹 BLOG POSTS (DYNAMIC FOLDER)
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Content", name: "body", widget: "markdown" }

  # 🔹 TESTIMONIALS (DYNAMIC FOLDER)
  - name: "testimonials"
    label: "Success Stories"
    folder: "content/testimonials"
    create: true
    fields:
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Quote", name: "quote", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  # 🔹 CTA SECTIONS (SINGLE FILE)
  - name: "cta"
    label: "Call-To-Action Sections"
    file: "content/sections/cta.json"
    fields:
      - { label: "Primary CTA Text", name: "primaryText", widget: "string" }
      - { label: "Primary CTA URL", name: "primaryUrl", widget: "string" }

  # 🔹 TRAININGS & WORKSHOPS (DYNAMIC FOLDER)
  - name: "workshops"
    label: "Trainings & Workshops"
    folder: "content/workshops"
    create: true
    fields:
      - { label: "Workshop Title", name: "title", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }

  # 🔹 EXPERT SPEAKERS (DYNAMIC FOLDER)
  - name: "speakers"
    label: "Expert Guest Speakers"
    folder: "content/speakers"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Bio", name: "bio", widget: "markdown" }

  # 🔹 FAQs (DYNAMIC FOLDER)
  - name: "faqs"
    label: "Frequently Asked Questions"
    folder: "content/faqs"
    create: true
    fields:
      - { label: "Question", name: "question", widget: "string" }
      - { label: "Answer", name: "answer", widget: "markdown" }

  # 🔹 ADDITIONAL SECTIONS (SMALLER CONTENT BLOCKS)
  - name: "liveSessions"
    label: "Dynamic LIVE Sessions"
    file: "content/sections/live-sessions.json"
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }

  - name: "expertSessions"
    label: "Access All Expert Sessions"
    file: "content/sections/expert-sessions.json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Session Details", name: "details", widget: "text" }

  - name: "missedDates"
    label: "Can't Make These Dates?"
    file: "content/sections/missed-dates.json"
    fields:
      - { label: "Message", name: "message", widget: "string" }

  - name: "questions"
    label: "Still have questions?"
    file: "content/sections/questions.json"
    fields:
      - { label: "FAQ Section Heading", name: "faqHeading", widget: "string" }
      - { label: "CTA Text", name: "ctaText", widget: "string" }
      - { label: "CTA URL", name: "ctaUrl", widget: "string" }

  - name: "resources"
    label: "Resources & Quick Links"
    file: "content/settings/resources.json"
    fields:
      - label: "Resource Links"
        name: "links"
        widget: "list"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }

  - name: "contact"
    label: "Contact Us"
    file: "content/settings/contact.json"
    fields:
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string" }
      - { label: "Address", name: "address", widget: "text" }
