backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} {{slug}}"
    update: "Update {{collection}} {{slug}}"
    delete: "Delete {{collection}} {{slug}}"
    uploadMedia: "[skip ci] Upload {{path}}"
    deleteMedia: "[skip ci] Delete {{path}}"

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: https://startsolo.in
display_url: https://startsolo.in
local_backend: true

collections:
  # 🌍 GLOBAL SETTINGS
  - name: "settings"
    label: "Site Settings"
    folder: "content/settings"
    create: false
    fields:
      - { label: "Site Title", name: "siteTitle", widget: "string" }
      - { label: "Site Description", name: "siteDescription", widget: "text" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Primary Color", name: "primaryColor", widget: "color" }
      - { label: "Font Family", name: "font", widget: "string" }
      - { label: "Google Analytics ID", name: "gaId", widget: "string" }
      - { label: "WhatsApp Button Text", name: "whatsappText", widget: "string" }
      - { label: "WhatsApp URL", name: "whatsappUrl", widget: "string" }

  # 📌 HEADER & FOOTER
  - name: "navigation"
    label: "Header & Footer"
    folder: "content/settings"
    create: false
    fields:
      - { label: "Menu Items", name: "menu", widget: "list", fields: [{ label: "Label", name: "label", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }
      - { label: "Quick Links", name: "quickLinks", widget: "list", fields: [{ label: "Label", name: "label", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }
      - { label: "Social Media", name: "social", widget: "object", fields: [{ label: "Instagram", name: "instagram", widget: "string" }, { label: "LinkedIn", name: "linkedin", widget: "string" }] }

  # 🎯 CONTENT SECTIONS
  - name: "sections"
    label: "Content Sections"
    folder: "content/sections"
    create: false
    fields:
      - { label: "Hero Heading", name: "heading", widget: "string" }
      - { label: "Hero Video ID", name: "videoId", widget: "string" }
      - { label: "Brand Logos", name: "logos", widget: "list", fields: [{ label: "Image", name: "image", widget: "image" }] }
      - { label: "Webinar Details", name: "details", widget: "markdown" }
      - { label: "Available Dates", name: "dates", widget: "list", fields: [{ label: "Date", name: "date", widget: "datetime" }, { label: "Time", name: "time", widget: "string" }] }
      - { label: "Testimonials", name: "quotes", widget: "list", fields: [{ label: "Quote", name: "quote", widget: "text" }, { label: "Author", name: "author", widget: "string" }] }
      - { label: "WhatsApp CTA", name: "ctaButton", widget: "object", fields: [{ label: "Text", name: "text", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }

  # 📚 BLOG
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  # 📄 STATIC PAGES
  - name: "pages"
    label: "Static Pages"
    folder: "content/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
