backend:
  name: git-gateway
  branch: main # Branch to update
  commit_messages:
    create: "Create {{collection}} {{slug}}"
    update: "Update {{collection}} {{slug}}"
    delete: "Delete {{collection}} {{slug}}"
    uploadMedia: "[skip ci] Upload {{path}}"
    deleteMedia: "[skip ci] Delete {{path}}"

site_url: https://startsolo.in
display_url: https://startsolo.in

# Media Storage
media_folder: "public/uploads"
public_folder: "/uploads"

local_backend: true

collections:
  # 🔹 SITE SETTINGS
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "content/settings/general.json"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: "string" }
          - { label: "Site Description", name: "siteDescription", widget: "text" }
          - { label: "Logo Image", name: "logoImage", widget: "image" }
          - { label: "Logo Text", name: "logoText", widget: "string", default: "Start Solo" }
          - { label: "Countdown Message", name: "countdownMessage", widget: "string", default: "Only {days} days left!" }
          - { label: "Countdown Target Date", name: "countdownTargetDate", widget: "datetime" }

  # 🔹 HEADER NAVIGATION
  - name: "navigation"
    label: "Header Navigation"
    file: "content/settings/navigation.json"
    fields:
      - label: "Navigation Links"
        name: "navLinks"
        widget: "list"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - label: "CTA Button"
        name: "ctaButton"
        widget: "object"
        fields:
          - { label: "Text", name: "text", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }

  # 🔹 HERO SECTION
  - name: "hero"
    label: "Hero Section"
    file: "content/sections/hero.json"
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Subheading", name: "subheading", widget: "text" }
      - { label: "CTA Text", name: "ctaText", widget: "string" }
      - { label: "CTA URL", name: "ctaUrl", widget: "string" }
      - { label: "Background Image", name: "backgroundImage", widget: "image" }

  # 🔹 TRAINING & WORKSHOPS (LOGO UPLOADS)
  - name: "training_workshops"
    label: "Training & Workshops"
    file: "content/sections/training_workshops.json"
    fields:
      - { label: "Title", name: "title", widget: "string", default: "Training & Workshops" }
      - label: "Logos"
        name: "logos"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image", media_folder: "public/uploads", public_folder: "/uploads" }
          - { label: "Alt Text", name: "alt", widget: "string" }

  # 🔹 WEBINAR INFO
  - name: "webinar_info"
    label: "Webinar Info"
    file: "content/sections/webinarInfo.json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Session Duration", name: "duration", widget: "string" }
      - { label: "Session Price", name: "price", widget: "string" }
      - { label: "Benefits", name: "benefits", widget: "list", fields: [{ label: "Point", name: "point", widget: "string" }] }

  # 🔹 TESTIMONIALS SECTION
  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Testimonial", name: "testimonial", widget: "text" }
      - { label: "Profile Image", name: "image", widget: "image" }

  # 🔹 COURSE OVERVIEW
  - name: "course"
    label: "Course Overview"
    file: "content/sections/course.json"
    fields:
      - { label: "Course Title", name: "title", widget: "string" }
      - { label: "Course Description", name: "description", widget: "text" }
      - { label: "Modules", name: "modules", widget: "list", fields: [{ label: "Module Name", name: "moduleName", widget: "string" }] }

  # 🔹 WEBINAR DATES & REGISTRATION
  - name: "webinarDates"
    label: "Webinar Dates"
    file: "content/sections/webinarDates.json"
    fields:
      - label: "Available Dates"
        name: "dates"
        widget: "list"
        fields:
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Spots Left", name: "spotsLeft", widget: "number" }
          - { label: "Registration Link", name: "registrationLink", widget: "string" }

  # 🔹 FOOTER SETTINGS
  - name: "footer"
    label: "Footer"
    file: "content/sections/footer.json"
    fields:
      - { label: "Footer Text", name: "footerText", widget: "string" }
      - label: "Social Links"
        name: "socialLinks"
        widget: "list"
        fields:
          - { label: "Platform", name: "platform", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }

