backend:
  name: git-gateway
  branch: main # Ensure updates go to the correct branch
  commit_messages:
    create: "Create {{collection}} {{slug}}"
    update: "Update {{collection}} {{slug}}"
    delete: "Delete {{collection}} {{slug}}"
    uploadMedia: "[skip ci] Upload {{path}}"
    deleteMedia: "[skip ci] Delete {{path}}"

# Site URL
site_url: https://startsolo.in
display_url: https://startsolo.in

# Media Uploads (Images, Videos, Logos)
media_folder: "public/uploads"
public_folder: "/uploads"

local_backend: true

collections:
  # 🛠 SITE SETTINGS (General, Branding, Navigation)
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "content/settings/general.json"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: "string" }
          - { label: "Site Description", name: "siteDescription", widget: "text" }
          - { label: "Logo Image", name: "logoImage", widget: "image" }
          - { label: "Cohort Start Date", name: "cohortStartDate", widget: "datetime" }
          - { label: "Countdown Timer", name: "countdownMessage", widget: "string", default: "Only {days} days left!" }

      - name: "branding"
        label: "Branding & Colors"
        file: "content/settings/branding.json"
        fields:
          - { label: "Primary Color", name: "primaryColor", widget: "color" }
          - { label: "Secondary Color", name: "secondaryColor", widget: "color" }
          - { label: "Typography", name: "typography", widget: "string", default: "sans-serif" }

      - name: "header"
        label: "Header & Navigation"
        file: "content/settings/header.json"
        fields:
          - { label: "Logo Image", name: "logoImage", widget: "image" }
          - { label: "Navigation Menu", name: "navLinks", widget: "list", fields: [{label: "Label", name: "label", widget: "string"}, {label: "URL", name: "url", widget: "string"}] }
          - { label: "CTA Button Text", name: "ctaText", widget: "string" }
          - { label: "CTA Button URL", name: "ctaUrl", widget: "string" }

  # 🔥 HOMEPAGE CONTENT SECTIONS
  - name: "homepage"
    label: "Homepage Sections"
    files:
      - name: "hero"
        label: "Hero Section"
        file: "content/homepage/hero.json"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "text" }
          - { label: "Video/Image Preview", name: "media", widget: "image" }
          - { label: "CTA Button Text", name: "ctaText", widget: "string" }
          - { label: "CTA Button URL", name: "ctaUrl", widget: "string" }

      - name: "why_attend"
        label: "Why Attend?"
        file: "content/homepage/why_attend.md"
        fields:
          - { label: "Main Text", name: "content", widget: "markdown" }
          - { label: "Learning Points", name: "learning_points", widget: "list", fields: [{ label: "Point", name: "point", widget: "string" }] }

      - name: "who_should_attend"
        label: "Who Should Attend?"
        file: "content/sections/course.json"
        fields:
          - { label: "Target Audience", name: "targetAudience", widget: "list", fields: [{ label: "Audience Type", name: "type", widget: "string" }] }

      - name: "course_overview"
        label: "Course Overview"
        file: "content/sections/course.json"
        fields:
          - { label: "Course Modules", name: "modules", widget: "list", fields: [{ label: "Module Name", name: "moduleName", widget: "string" }, { label: "Description", name: "description", widget: "text" }] }

      - name: "testimonials"
        label: "Testimonials"
        file: "content/homepage/testimonials.md"
        fields:
          - { label: "Success Stories", name: "stories", widget: "list", fields: [{ label: "Name", name: "name", widget: "string" }, { label: "Quote", name: "quote", widget: "text" }] }

      - name: "brand_logos"
        label: "Training & Workshop Logos"
        file: "content/homepage/brand_logos.md"
        fields:
          - { label: "Logos", name: "logos", widget: "list", fields: [{ label: "Image", name: "image", widget: "image" }, { label: "Alt Text", name: "alt", widget: "string" }] }

  # 📅 WEBINAR DETAILS
  - name: "webinars"
    label: "Webinar Sessions"
    files:
      - name: "session_details"
        label: "Session Details"
        file: "content/homepage/session_details.md"
        fields:
          - { label: "Duration", name: "duration", widget: "string" }
          - { label: "Price", name: "price", widget: "string" }

      - name: "webinar_dates"
        label: "Available Dates"
        file: "content/homepage/webinar_dates.md"
        fields:
          - { label: "Session Dates", name: "dates", widget: "list", fields: [{ label: "Date", name: "date", widget: "datetime" }, { label: "Time", name: "time", widget: "string" }, { label: "Spots Left", name: "spotsLeft", widget: "number" }, { label: "Registration URL", name: "registrationUrl", widget: "string" }] }

  # 🔻 FOOTER CONTENT
  - name: "footer"
    label: "Footer Content"
    file: "content/sections/footer.json"
    fields:
      - { label: "Quick Links", name: "links", widget: "list", fields: [{ label: "Label", name: "label", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }
      - { label: "Social Media Links", name: "socialLinks", widget: "list", fields: [{ label: "Platform", name: "platform", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }
