backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} {{slug}}"
    update: "Update {{collection}} {{slug}}"
    delete: "Delete {{collection}} {{slug}}"
    uploadMedia: "[skip ci] Upload {{path}}"
    deleteMedia: "[skip ci] Delete {{path}}"

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: https://startsolo.in
display_url: https://startsolo.in
local_backend: true

collections:
  - name: "settings"
    label: "Global Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "content/settings/general.json"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: "string" }
          - { label: "Site Description", name: "siteDescription", widget: "text" }
          - { label: "Logo", name: "logo", widget: "image" }
      - name: "seo"
        label: "SEO Settings"
        file: "content/settings/seo.json"
        fields:
          - { label: "Meta Title", name: "metaTitle", widget: "string" }
          - { label: "Meta Description", name: "metaDescription", widget: "text" }
      - name: "branding"
        label: "Branding & Theme"
        file: "content/settings/branding.json"
        fields:
          - { label: "Primary Color", name: "primaryColor", widget: "color" }
          - { label: "Font", name: "font", widget: "string" }
      - name: "integrations"
        label: "Third-Party Integrations"
        file: "content/settings/integrations.json"
        fields:
          - { label: "WhatsApp CTA Text", name: "whatsappText", widget: "string" }
          - { label: "WhatsApp Link", name: "whatsappUrl", widget: "string" }
          - { label: "WhatsApp Sticky CTA Enabled", name: "whatsappSticky", widget: "boolean", default: true }

  - name: "navigation"
    label: "Header & Footer"
    files:
      - name: "header"
        label: "Header"
        file: "content/settings/header.json"
        fields:
          - label: "Menu Items"
            name: "menu"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
      - name: "footer"
        label: "Footer"
        file: "content/settings/footer.json"
        fields:
          - { label: "Quick Links", name: "quickLinks", widget: "list", fields: [{ label: "Label", name: "label", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }
          - { label: "Social Media", name: "social", widget: "object", fields: [{ label: "Instagram", name: "instagram", widget: "string" }, { label: "LinkedIn", name: "linkedin", widget: "string" }] }
          - { label: "Logos & Partnerships", name: "logos", widget: "list", fields: [{ label: "Image", name: "image", widget: "image" }, { label: "Alt Text", name: "alt", widget: "string" }] }

  - name: "sections"
    label: "Content Sections"
    files:
      - name: "hero"
        label: "Hero Section"
        file: "content/sections/hero.json"
        fields:
          - { label: "Main Heading", name: "heading", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "string" }
          - { label: "Video ID", name: "videoId", widget: "string" }
      - name: "course_overview"
        label: "Course Overview"
        file: "content/sections/course_overview.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Duration", name: "duration", widget: "string" }
      - name: "curriculum"
        label: "Course Curriculum"
        file: "content/sections/curriculum.json"
        fields:
          - { label: "Modules", name: "modules", widget: "list", fields: [{ label: "Week", name: "week", widget: "string" }, { label: "Title", name: "title", widget: "string" }, { label: "Lessons", name: "lessons", widget: "list", fields: [{ label: "Lesson Title", name: "lesson", widget: "string" }, { label: "Description", name: "description", widget: "text" }] }] }
      - name: "value_adds"
        label: "Value Adds"
        file: "content/sections/value_adds.json"
        fields:
          - { label: "Items", name: "items", widget: "list", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Description", name: "description", widget: "text" }] }
      - name: "faq"
        label: "Frequently Asked Questions"
        file: "content/sections/faq.json"
        fields:
          - { label: "Questions", name: "questions", widget: "list", fields: [{ label: "Question", name: "question", widget: "string" }, { label: "Answer", name: "answer", widget: "text" }] }
      - name: "testimonials"
        label: "Success Stories & Testimonials"
        file: "content/sections/testimonials.json"
        fields:
          - { label: "Testimonials", name: "testimonials", widget: "list", fields: [{ label: "Name", name: "name", widget: "string" }, { label: "Title", name: "title", widget: "string" }, { label: "Review", name: "review", widget: "text" }, { label: "Image", name: "image", widget: "image" }, { label: "Rating", name: "rating", widget: "number", default: 5 }] }
      - name: "cta"
        label: "Final CTA"
        file: "content/sections/cta.json"
        fields:
          - { label: "CTA Text", name: "ctaText", widget: "string" }
          - { label: "CTA Link", name: "ctaUrl", widget: "string" }
      - name: "trainers"
        label: "Trainers & Expert Speakers"
        file: "content/sections/trainers.json"
        fields:
          - { label: "Speakers", name: "speakers", widget: "list", fields: [{ label: "Name", name: "name", widget: "string" }, { label: "Title", name: "title", widget: "string" }, { label: "Bio", name: "bio", widget: "text" }, { label: "Image", name: "image", widget: "image" }, { label: "Speaking Topic", name: "topic", widget: "string" }] }
