backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} {{slug}}"
    update: "Update {{collection}} {{slug}}"
    delete: "Delete {{collection}} {{slug}}"
    uploadMedia: "[skip ci] Upload {{path}}"
    deleteMedia: "[skip ci] Delete {{path}}"

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: https://startsolo.in
display_url: https://startsolo.in
local_backend: true

collections:
  - name: "settings"
    label: "Global Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "content/settings/general.json"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: "string", hint: "Max 60 characters" }
          - { label: "Site Description", name: "siteDescription", widget: "text", hint: "Max 160 characters" }
          - { label: "Logo", name: "logo", widget: "image", hint: "200x50px, max 100KB, SVG preferred" }
      - name: "seo"
        label: "SEO Settings"
        file: "content/settings/seo.json"
        fields:
          - { label: "Meta Title", name: "metaTitle", widget: "string" }
          - { label: "Meta Description", name: "metaDescription", widget: "text", hint: "Max 160 characters" }
          - { label: "Open Graph Image", name: "ogImage", widget: "image", hint: "1200x630px, max 300KB" }
          - { label: "Schema Markup", name: "schemaMarkup", widget: "text" }
      - name: "branding"
        label: "Branding & Theme"
        file: "content/settings/branding.json"
        fields:
          - { label: "Primary Color", name: "primaryColor", widget: "color" }
          - { label: "Font", name: "font", widget: "string" }
      - name: "integrations"
        label: "Third-Party Integrations"
        file: "content/settings/integrations.json"
        fields:
          - { label: "WhatsApp CTA Text", name: "whatsappText", widget: "string" }
          - { label: "WhatsApp Link", name: "whatsappUrl", widget: "string" }
          - { label: "WhatsApp Sticky CTA Enabled", name: "whatsappSticky", widget: "boolean", default: true }
          - { label: "Floating Registration CTA", name: "floatingCTA", widget: "boolean", default: true }
          - { label: "Popup Notifications", name: "popupNotifications", widget: "list", fields: [{ label: "Message", name: "message", widget: "string" }, { label: "Trigger Event", name: "trigger", widget: "string" }] }

  - name: "navigation"
    label: "Header & Footer"
    files:
      - name: "header"
        label: "Header"
        file: "content/settings/header.json"
        fields:
          - label: "Menu Items"
            name: "menu"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string", hint: "Max 20 characters" }
              - { label: "URL", name: "url", widget: "string" }
      - name: "footer"
        label: "Footer"
        file: "content/settings/footer.json"
        fields:
          - { label: "Quick Links", name: "quickLinks", widget: "list", fields: [{ label: "Label", name: "label", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }
          - { label: "Social Media", name: "social", widget: "object", fields: [{ label: "Instagram", name: "instagram", widget: "string" }, { label: "LinkedIn", name: "linkedin", widget: "string" }, { label: "Twitter", name: "twitter", widget: "string" }, { label: "Facebook", name: "facebook", widget: "string" }, { label: "YouTube", name: "youtube", widget: "string" }] }
          - { label: "Newsletter Signup", name: "newsletter", widget: "string" }

  - name: "sections"
    label: "Content Sections"
    files:
      - name: "journey"
        label: "Journey/Steps Section"
        file: "content/sections/journey.json"
        fields:
          - { label: "Step 1 Description", name: "step1", widget: "string" }
          - { label: "Step 2 Description", name: "step2", widget: "string" }
          - { label: "CTA Text", name: "cta", widget: "string" }
      - name: "whatsapp_hub"
        label: "WhatsApp Hub Section"
        file: "content/sections/whatsapp_hub.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Benefits", name: "benefits", widget: "list", fields: [{ label: "Benefit", name: "benefit", widget: "string" }] }
          - { label: "Join Button Text", name: "buttonText", widget: "string" }
          - { label: "Join Button Link", name: "buttonLink", widget: "string" }
      - name: "guarantee"
        label: "Guarantee Section"
        file: "content/sections/guarantee.json"
        fields:
          - { label: "Guarantee Details", name: "details", widget: "text" }
          - { label: "Terms & Conditions", name: "terms", widget: "text" }
          - { label: "Trust Indicators", name: "indicators", widget: "list", fields: [{ label: "Indicator", name: "indicator", widget: "string" }] }
  
  - name: "popup_notifications"
    label: "Popup/Notification System"
    file: "content/settings/popups.json"
    fields:
      - { label: "Notification Messages", name: "messages", widget: "list", fields: [{ label: "Message", name: "message", widget: "string" }, { label: "Trigger", name: "trigger", widget: "string" }] }
