backend:
  name: git-gateway
  branch: main # Branch to update
  commit_messages:
    create: "Create {{collection}} {{slug}}"
    update: "Update {{collection}} {{slug}}"
    delete: "Delete {{collection}} {{slug}}"
    uploadMedia: "[skip ci] Upload {{path}}"
    deleteMedia: "[skip ci] Delete {{path}}"

# Site Settings
site_url: https://startsolo.in
display_url: https://startsolo.in

# Media Handling
media_folder: "public/uploads"
public_folder: "/uploads"

# Enable local backend for development
local_backend: true

collections:
  # ✅ SITE SETTINGS (Uses files)
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "content/settings/general.json"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: "string" }
          - { label: "Site Description", name: "siteDescription", widget: "text" }
      - name: "branding"
        label: "Branding & Colors"
        file: "content/settings/branding.json"
        fields:
          - { label: "Primary Color", name: "primaryColor", widget: "color", default: "#e57341" }
          - { label: "Secondary Color", name: "secondaryColor", widget: "color", default: "#0097b2" }
      - name: "countdown"
        label: "Countdown Timer"
        file: "content/settings/countdown.json"
        fields:
          - { label: "Enable", name: "enabled", widget: "boolean", default: true }
          - { label: "End Date", name: "endDate", widget: "datetime" }
          - { label: "Message", name: "message", widget: "string" }

  # ✅ NAVIGATION SETTINGS
  - name: "header"
    label: "Header Settings"
    file: "content/settings/header.json"
    fields:
      - { label: "Logo Image", name: "logoImage", widget: "image" }
      - label: "Navigation Links"
        name: "navLinks"
        widget: "list"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }

  # ✅ DYNAMIC PAGES (Uses folder)
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Meta Description", name: "metaDescription", widget: "text" }
      - { label: "Content", name: "body", widget: "markdown" }

  # ✅ BLOG POSTS (Uses folder)
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  # ✅ TESTIMONIALS (Uses folder)
  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Testimonial", name: "testimonial", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  # ✅ EXPERT SPEAKERS (Uses folder)
  - name: "experts"
    label: "Expert Speakers"
    folder: "content/experts"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Topic", name: "topic", widget: "string" }
      - { label: "Session Date", name: "sessionDate", widget: "datetime" }
      - { label: "Profile Image", name: "profileImage", widget: "image" }

  # ✅ TRAINING & WORKSHOPS (Uses files)
  - name: "training"
    label: "Training & Workshops"
    file: "content/sections/training.json"
    fields:
      - { label: "Featured Logos", name: "logos", widget: "list", field: { label: "Logo", name: "logo", widget: "image" } }

  # ✅ WEBINAR SESSIONS (Uses files)
  - name: "webinarSessions"
    label: "Webinar Sessions"
    files:
      - name: "dates"
        label: "Available Dates"
        file: "content/sections/webinarDates.json"
        fields:
          - label: "Available Dates"
            name: "dates"
            widget: "list"
            fields:
              - { label: "Session ID", name: "id", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Spots Left", name: "spotsLeft", widget: "number" }
              - { label: "Registration Link", name: "registrationLink", widget: "string" }

  # ✅ FOOTER CONTENT (Uses files)
  - name: "footer"
    label: "Footer"
    file: "content/sections/footer.json"
    fields:
      - { label: "Quick Links", name: "quickLinks", widget: "list", field: { label: "Link", name: "link", widget: "string" } }
      - { label: "Social Media", name: "socialMedia", widget: "list", field: { label: "Platform", name: "platform", widget: "string" } }

  # ✅ COURSE OVERVIEW & CURRICULUM (Uses files)
  - name: "course"
    label: "Course Overview"
    file: "content/sections/course.json"
    fields:
      - { label: "Course Modules", name: "modules", widget: "list", field: { label: "Module Title", name: "title", widget: "string" } }

  # ✅ HOME PAGE SECTIONS (Uses files)
  - name: "sections"
    label: "Content Sections"
    files:
      - name: "hero"
        label: "Hero Section"
        file: "content/sections/hero.json"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "text" }
      - name: "why_attend"
        label: "Why Attend"
        file: "content/sections/why_attend.json"
        fields:
          - { label: "Reasons", name: "reasons", widget: "list", field: { label: "Reason", name: "text", widget: "string" } }
