backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} {{slug}}"
    update: "Update {{collection}} {{slug}}"
    delete: "Delete {{collection}} {{slug}}"
    uploadMedia: "[skip ci] Upload {{path}}"
    deleteMedia: "[skip ci] Delete {{path}}"

site_url: https://startsolo.in
display_url: https://startsolo.in

media_folder: "public/uploads"
public_folder: "/uploads"

local_backend: true

collections:
  # 🛠️ SITE SETTINGS
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "content/settings/general.json"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: "string" }
          - { label: "Site Description", name: "siteDescription", widget: "text" }
          - { label: "Logo", name: "logo", widget: "image" }
      - name: "branding"
        label: "Branding & Colors"
        file: "content/settings/branding.json"
        fields:
          - { label: "Primary Color", name: "primaryColor", widget: "color" }
          - { label: "Secondary Color", name: "secondaryColor", widget: "color" }

  # 📖 PAGES
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Meta Description", name: "metaDescription", widget: "text" }
      - { label: "Content", name: "body", widget: "markdown" }

  # 📝 BLOG
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Content", name: "body", widget: "markdown" }

  # ⭐ TESTIMONIALS
  - name: "testimonials"
    label: "Success Stories"
    folder: "content/testimonials"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Quote", name: "quote", widget: "text" }

  # 🎓 TRAININGS & WORKSHOPS
  - name: "trainings"
    label: "Trainings & Workshops"
    file: "content/sections/trainings.json"
    fields:
      - label: "Partner Logos"
        name: "logos"
        widget: "list"
        field: { label: "Logo", name: "logo", widget: "image" }

  # 🕒 COUNTDOWN TIMER
  - name: "countdown"
    label: "Countdown Timer"
    file: "content/settings/countdown.json"
    fields:
      - { label: "Enable", name: "enabled", widget: "boolean" }
      - { label: "End Date", name: "endDate", widget: "datetime" }
      - { label: "Message", name: "message", widget: "string" }

  # 🎤 EXPERT SPEAKERS
  - name: "speakers"
    label: "Learn from the Best"
    folder: "content/speakers"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Bio", name: "bio", widget: "markdown" }

  # 🎯 CTA SECTIONS
  - name: "cta"
    label: "Call-to-Actions"
    file: "content/sections/cta.json"
    fields:
      - { label: "Primary CTA", name: "primary", widget: "object", fields: [{ label: "Text", name: "text", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }
      - { label: "Community CTA", name: "community", widget: "object", fields: [{ label: "Text", name: "text", widget: "string" }, { label: "URL", name: "url", widget: "string" }] }

  # 🗓️ WEBINAR SESSIONS
  - name: "webinarSessions"
    label: "Webinar Sessions"
    file: "content/sections/webinar-dates.json"
    fields:
      - label: "Available Dates"
        name: "dates"
        widget: "list"
        fields:
          - { label: "Session ID", name: "id", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Spots Left", name: "spotsLeft", widget: "number" }
          - { label: "Registration Link", name: "registrationLink", widget: "string" }

  # 🔗 FOOTER SETTINGS
  - name: "footer"
    label: "Footer Links"
    file: "content/settings/footer.json"
    fields:
      - label: "Quick Links"
        name: "quickLinks"
        widget: "list"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - label: "Social Media"
        name: "socialMedia"
        widget: "object"
        fields:
          - { label: "Twitter", name: "twitter", widget: "string" }
          - { label: "Instagram", name: "instagram", widget: "string" }
          - { label: "LinkedIn", name: "linkedin", widget: "string" }
      - label: "Legal Links"
        name: "legalLinks"
        widget: "list"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }

