backend:
  name: git-gateway
  branch: main # Branch to update
  commit_messages:
    create: "Create {{collection}} {{slug}}"
    update: "Update {{collection}} {{slug}}"
    delete: "Delete {{collection}} {{slug}}"
    uploadMedia: "[skip ci] Upload {{path}}"
    deleteMedia: "[skip ci] Delete {{path}}"

# This line should match your site URL
site_url: https://startsolo.in
display_url: https://startsolo.in

# Media files will be stored in the repo under public/uploads
media_folder: "public/uploads"
public_folder: "/uploads"

# Enable local backend for development
local_backend: true

collections:
  # 🔹 **Site Settings**
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "src/content/settings/general.json"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: "string" }
          - { label: "Site Description", name: "siteDescription", widget: "text" }
          - { label: "Logo Image", name: "logoImage", widget: "image" }
          - { label: "Cohort Start Date", name: "cohortStartDate", widget: "datetime" }
          - { label: "Next Cohort Start Date", name: "nextCohortStartDate", widget: "datetime" }
          
      - name: "countdown"
        label: "Countdown Timer"
        file: "src/content/settings/countdown.json"
        fields:
          - { label: "Enable Countdown", name: "enabled", widget: "boolean", default: true }
          - { label: "Countdown Message", name: "message", widget: "string" }
          - { label: "Target Date", name: "targetDate", widget: "datetime" }

      - name: "header"
        label: "Header & Navigation"
        file: "src/content/settings/header.json"
        fields:
          - { label: "Logo Image", name: "logoImage", widget: "image" }
          - label: "Navigation Links"
            name: "navLinks"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          - label: "CTA Button"
            name: "ctaButton"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

  # 🔹 **Page Sections**
  - name: "homepage"
    label: "Homepage Sections"
    files:
      - name: "hero"
        label: "Hero Section"
        file: "src/content/sections/hero.json"
        fields:
          - { label: "Main Heading", name: "heading", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "text" }
          - { label: "Hero Image", name: "heroImage", widget: "image" }
          - { label: "CTA Button Text", name: "ctaText", widget: "string" }
          - { label: "CTA Button URL", name: "ctaUrl", widget: "string" }

      - name: "trainings"
        label: "Trainings & Workshops"
        file: "src/content/sections/trainings.json"
        fields:
          - label: "Workshops"
            name: "workshops"
            widget: "list"
            fields:
              - { label: "Workshop Name", name: "name", widget: "string" }
              - { label: "Workshop Logo", name: "logo", widget: "image" }
              - { label: "Description", name: "description", widget: "text" }

      - name: "webinar"
        label: "Webinar Info"
        file: "src/content/sections/webinar.json"
        fields:
          - { label: "Session Title", name: "sessionTitle", widget: "string" }
          - { label: "Session Duration", name: "duration", widget: "string" }
          - { label: "Session Price", name: "price", widget: "string" }

      - name: "testimonials"
        label: "Testimonials"
        file: "src/content/sections/testimonials.json"
        fields:
          - label: "Featured Testimonials"
            name: "featured"
            widget: "list"
            fields:
              - { label: "Author", name: "author", widget: "string" }
              - { label: "Quote", name: "quote", widget: "text" }

      - name: "course"
        label: "Course Overview"
        file: "src/content/sections/course.json"
        fields:
          - { label: "Course Name", name: "courseName", widget: "string" }
          - { label: "Modules", name: "modules", widget: "list", fields: [{ label: "Module Title", name: "title", widget: "string" }] }

      - name: "faq"
        label: "Frequently Asked Questions"
        file: "src/content/sections/faq.json"
        fields:
          - label: "Questions"
            name: "questions"
            widget: "list"
            fields:
              - { label: "Question", name: "question", widget: "string" }
              - { label: "Answer", name: "answer", widget: "text" }

  # 🔹 **Events & Webinar Calendar**
  - name: "events"
    label: "Events & Dates"
    file: "src/content/events.json"
    fields:
      - label: "Upcoming Events"
        name: "upcoming"
        widget: "list"
        fields:
          - { label: "Event Name", name: "event_name", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Location", name: "location", widget: "string" }
          - { label: "Registration Link", name: "registration_link", widget: "string" }

  # 🔹 **Footer**
  - name: "footer"
    label: "Footer Settings"
    file: "src/content/settings/footer.json"
    fields:
      - label: "Quick Links"
        name: "quickLinks"
        widget: "list"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - label: "Social Media"
        name: "socialLinks"
        widget: "list"
        fields:
          - { label: "Platform", name: "platform", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - label: "Contact Info"
        name: "contact"
        widget: "object"
        fields:
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
