backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: https://startsolo.in
display_url: https://startsolo.in

collections:
  # 🔹 1. SITE SETTINGS (Global)
  - name: "settings"
    label: "Global Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "content/settings/general.json"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: "string" }
          - { label: "Site URL", name: "siteUrl", widget: "string" }
          - { label: "Google Analytics ID", name: "gaId", widget: "string", required: false }

      - name: "branding"
        label: "Branding & Colors"
        file: "content/settings/branding.json"
        fields:
          - { label: "Primary Color", name: "primaryColor", widget: "color" }
          - { label: "Secondary Color", name: "secondaryColor", widget: "color" }
          - { label: "Typography", name: "typography", widget: "string" }

      - name: "header"
        label: "Header & Navigation"
        file: "content/settings/header.json"
        fields:
          - { label: "Logo Image", name: "logo", widget: "image" }
          - { label: "Navigation Links", name: "navLinks", widget: "list", fields: 
              [{ label: "Label", name: "label", widget: "string" },
               { label: "URL", name: "url", widget: "string" }] }

      - name: "footer"
        label: "Footer & Links"
        file: "content/settings/footer.json"
        fields:
          - { label: "Quick Links", name: "quickLinks", widget: "list", fields: 
              [{ label: "Label", name: "label", widget: "string" },
               { label: "URL", name: "url", widget: "string" }] }
          - { label: "Social Media", name: "socialMedia", widget: "object", fields:
              [{ label: "Twitter", name: "twitter", widget: "string" },
               { label: "Instagram", name: "instagram", widget: "string" },
               { label: "LinkedIn", name: "linkedin", widget: "string" }] }

  # 🔹 2. PAGE SECTIONS
  - name: "sections"
    label: "Page Sections"
    files:
      - name: "hero"
        label: "Hero Section"
        file: "content/sections/hero.json"
        fields:
          - { label: "Main Heading", name: "title", widget: "string" }
          - { label: "Subheading", name: "subtitle", widget: "text" }
          - { label: "Video ID", name: "videoId", widget: "string", required: false }
          - { label: "Preview Image", name: "previewImage", widget: "image", required: false }

      - name: "featuredIn"
        label: "Trainings & Workshops"
        file: "content/sections/featuredIn.json"
        fields:
          - { label: "Logos", name: "logos", widget: "list", field: { label: "Logo", name: "image", widget: "image" } }

      - name: "webinarInfo"
        label: "Why Attend This Session"
        file: "content/sections/webinarInfo.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Benefits", name: "benefits", widget: "list", field: { label: "Point", name: "text", widget: "text" } }

      - name: "course"
        label: "The Full Program"
        file: "content/sections/course.json"
        fields:
          - { label: "Overview", name: "overview", widget: "markdown" }
          - { label: "Curriculum", name: "curriculum", widget: "markdown" }
          - { label: "What You'll Gain", name: "gains", widget: "list", field: { label: "Point", name: "text", widget: "text" } }

      - name: "testimonials"
        label: "Success Stories"
        file: "content/sections/testimonials.json"
        fields:
          - { label: "Featured Stories", name: "featured", widget: "list", fields:
              [{ label: "Name", name: "name", widget: "string" },
               { label: "Quote", name: "quote", widget: "text" },
               { label: "Image", name: "image", widget: "image" }] }

      - name: "cta"
        label: "Final Call to Action"
        file: "content/sections/cta.json"
        fields:
          - { label: "Button Text", name: "text", widget: "string" }
          - { label: "Button URL", name: "url", widget: "string" }

  # 🔹 3. DYNAMIC COLLECTIONS (Folder-Based)
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "webinarDates"
    label: "Webinar Dates"
    folder: "content/webinarDates"
    create: true
    fields:
      - { label: "Session Date", name: "date", widget: "datetime" }
      - { label: "Available Spots", name: "spotsLeft", widget: "number" }
      - { label: "Registration Link", name: "registrationLink", widget: "string" }

  - name: "experts"
    label: "Expert Speakers"
    folder: "content/experts"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
      - { label: "Photo", name: "photo", widget: "image" }

---
🚀 **Now replace the existing `config.yml` with this and deploy!** Let me know if you need any adjustments.
