backend:
  name: git-gateway
  branch: main # Branch to update
  commit_messages:
    create: "Create {{collection}} {{slug}}"
    update: "Update {{collection}} {{slug}}"
    delete: "Delete {{collection}} {{slug}}"
    uploadMedia: "[skip ci] Upload {{path}}"
    deleteMedia: "[skip ci] Delete {{path}}"

# Site URL
site_url: https://startsolo.in
display_url: https://startsolo.in

# Media settings
media_folder: "public/uploads"
public_folder: "/uploads"

# Enable local backend
local_backend: true

collections:
  # 🌍 SITE SETTINGS (Uses "files" for single-instance settings)
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "content/settings/general.json"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: "string" }
          - { label: "Site Description", name: "siteDescription", widget: "text" }
          - { label: "Logo Image", name: "logoImage", widget: "image" }
          - { label: "Primary Color", name: "primaryColor", widget: "color" }

      - name: "header"
        label: "Header Settings"
        file: "content/settings/header.json"
        fields:
          - { label: "Logo Text", name: "logoText", widget: "string" }
          - { label: "Logo Image", name: "logoImage", widget: "image" }
          - label: "Navigation Links"
            name: "navLinks"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

  # 📝 BLOG POSTS (Uses "folder" for multiple blog posts)
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  # 📄 PAGES (Uses "folder" for dynamic pages)
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Meta Description", name: "metaDescription", widget: "text" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Show in Navigation", name: "showInNav", widget: "boolean" }

  # ⭐ TESTIMONIALS (Uses "folder" for multiple testimonials)
  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Testimonial", name: "testimonial", widget: "text" }
      - { label: "Photo", name: "photo", widget: "image" }

  # 🎓 TRAINING & WORKSHOPS (Uses "files" for logos and partners)
  - name: "trainings"
    label: "Trainings & Workshops"
    files:
      - name: "logos"
        label: "Partner Logos"
        file: "content/trainings/logos.json"
        fields:
          - label: "Logos"
            name: "logos"
            widget: "list"
            fields:
              - { label: "Logo Name", name: "name", widget: "string" }
              - { label: "Logo Image", name: "image", widget: "image" }

  # 📅 WEBINAR SESSIONS (Uses "files" for available dates)
  - name: "webinarSessions"
    label: "Webinar Sessions"
    files:
      - name: "dates"
        label: "Available Dates"
        file: "content/sections/webinarDates.json"
        fields:
          - label: "Available Dates"
            name: "dates"
            widget: "list"
            fields:
              - { label: "Session ID", name: "id", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Spots Left", name: "spotsLeft", widget: "number" }
              - { label: "Registration Link", name: "registrationLink", widget: "string" }

  # ⏳ COUNTDOWN TIMER (Uses "files" for settings)
  - name: "countdown"
    label: "Countdown Timer"
    files:
      - name: "timer"
        label: "Countdown Timer Settings"
        file: "content/settings/countdown.json"
        fields:
          - { label: "Enable Countdown", name: "enabled", widget: "boolean" }
          - { label: "Target Date", name: "targetDate", widget: "datetime" }
          - { label: "Message", name: "message", widget: "string" }
