backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "content/settings/general.json"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: "string" }
          - { label: "Logo Image", name: "logoImage", widget: "image" }
      - name: "branding"
        label: "Branding & Colors"
        file: "content/settings/branding.json"
        fields:
          - { label: "Primary Color", name: "primaryColor", widget: "color" }
          - { label: "Secondary Color", name: "secondaryColor", widget: "color" }

  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Testimonial", name: "testimonial", widget: "text" }

  - name: "trainings"
    label: "Trainings & Workshops"
    files:
      - name: "logos"
        label: "Partner Logos"
        file: "content/trainings/logos.json"
        fields:
          - { label: "Logos", name: "logos", widget: "list", field: { label: "Logo", name: "logo", widget: "image" } }

  - name: "webinarSessions"
    label: "Webinar Sessions"
    folder: "content/webinars"
    create: true
    fields:
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Registration Link", name: "registrationLink", widget: "string" }

  - name: "countdown"
    label: "Countdown Timer"
    files:
      - name: "timer"
        label: "Countdown Settings"
        file: "content/settings/countdown.json"
        fields:
          - { label: "Enable Countdown", name: "enabled", widget: "boolean" }
          - { label: "Target Date", name: "targetDate", widget: "datetime" }
